<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Ganeshs-MacBook-Pro.local" failures="1" tests="5" name="com.testng.tests.SalesforceLoginTest" time="27.803" errors="0" timestamp="22 Nov 2023 05:32:20 GMT">
  <testcase classname="com.testng.tests.SalesforceLoginTest" name="loginvalid" time="7.370"/>
  <testcase classname="com.testng.tests.SalesforceLoginTest" name="loginByForgotPassword" time="5.064"/>
  <testcase classname="com.testng.tests.SalesforceLoginTest" name="loginByInvalidPassword" time="2.869">
    <failure message="expected:&lt;Please [check your username and password. If you still can&#039;t log in, contact your Salesforce administrator].&gt; but was:&lt;Please [enter your password].&gt;" type="junit.framework.ComparisonFailure">
      <![CDATA[junit.framework.ComparisonFailure: expected:<Please [check your username and password. If you still can't log in, contact your Salesforce administrator].> but was:<Please [enter your password].>
	at junit.framework.Assert.assertEquals(Assert.java:85)
	at junit.framework.Assert.assertEquals(Assert.java:91)
	at com.testng.base.BaseTest.compareText(BaseTest.java:48)
	at com.testng.tests.SalesforceLoginTest.loginByInvalidPassword(SalesforceLoginTest.java:92)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:282)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:83)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:114)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
    </failure>
  </testcase> <!-- loginByInvalidPassword -->
  <testcase classname="com.testng.tests.SalesforceLoginTest" name="loginByrememberme" time="8.744"/>
  <testcase classname="com.testng.tests.SalesforceLoginTest" name="loginerrormsg" time="3.756"/>
</testsuite> <!-- com.testng.tests.SalesforceLoginTest -->
